env:
  RUBY_VERSION: 2.7.1

name: simple-rack-app ci
on: push

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install rubocop
        run: gem install rubocop
      - name: Run rubocop
        run: rubocop

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install dependencies
        run: gem install bundler && bundler install
      - name: Run tests
        run: bundler exec rspec
